version: '3.8'

services:
  api-service:
    build: 
      context: ./services/api-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=development
      - PORT=8080
    volumes:
      - ./services/api-service:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker-service:
    build: 
      context: ./services/worker-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ENV=development
      - PORT=8080
    volumes:
      - ./services/worker-service:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: cloud-run-services
    driver: bridge 